### ISSUE TITLE
Liferay 6.1.1 GA2

### ISSUE THREAD

**Issue by kidata** [michalmela/jmelon-quiz-portlet#1]
I've uncommented all the 6.1.0 properties, tlds e.g. and the portlet works fine in 6.1.0 GA1

But we're using 6.1.1 GA2, so i've changed pom.xml to <liferay.version>6.1.1</liferay.version> and can install it, but i get this error when adding it to a page:

ERROR [http-bio-8080-exec-94](FrameworkPortlet.java:559) - Could not complete request
java.io.FileNotFoundException: The requested resource (/quiz-portlet/WEB-INF/servlet/view/portal/quiz/view) is not available

Is it possible to get this working in 6.1.1 GA2?

**Comment by michalmela** [comment]
Thanks for feedback!
Isn't this the same issue as http://www.liferay.com/community/forums/-/message_boards/message/16173105 or https://issues.liferay.com/browse/LPS-29103 ?. If so, no spring portlets will run on your Liferay. You may manually fix the web.xml after initial portlet deployment (i.e. after Liferay messes it up), but it would probably be best to clone Liferay community sources, look up any commits marked with LPS-29103 and patch your portal-impl.jar manually. Personally I got used to it and have a whole workflow around patching Liferay CE, otherwise most CE versions would be unusable, security issues-ridden minefields.
If it's not the same issue (i.e. you are able to verifty that web.xml isn't messed up after portlet deployment) then let me know and I'll have a look at it.

**Comment by kidata** [comment]
Patching the portal-impl.jar with the provided patch from vpugar fixed the problem! Thanks, this is quite awesome, also for other Spring-Portlets we use! 
Now i will take a deeper look on the quiz.
Thanks again.
